version: '3'
services:
  common:
    build:
      context: ./petplanet-common
      dockerfile: Dockerfile
  pet:
    build:
      context: ./petplanet-pet
      dockerfile: Dockerfile
    container_name: petplanet-pet
    ports:
      - "8881:8881"
  post:
    build:
      context: ./petplanet-post
      dockerfile: Dockerfile
    container_name: petplanet-post
    ports:
      - "8882:8882"
  user:
    build:
      context: ./petplanet-user
      dockerfile: Dockerfile
    container_name: petplanet-user
    ports:
      - "8883:8883"
  api:
    build:
      context: ./petplanet-api
      dockerfile: Dockerfile
    container_name: petplanet-api
    ports:
      - "8885:8885"
