version: '3'
services:
  parent:
    build:
      context: .
      dockerfile: Dockerfile
    image: petplanet-parent:latest
  pet:
    build:
      context: ./petplanet-pet
      dockerfile: Dockerfile
    image: petplanet-pet-image:latest
#    container_name: petplanet-pet-container
#    ports:
#      - "8881:8881"
  post:
    build:
      context: ./petplanet-post
      dockerfile: Dockerfile
    image: petplanet-post-image:latest
#    container_name: petplanet-post-container
#    ports:
#      - "8882:8882"
  user:
    build:
      context: ./petplanet-user
      dockerfile: Dockerfile
    image: petplanet-user-image:latest
#    container_name: petplanet-user-container
#    ports:
#      - "8883:8883"
#  api:
#    build:
#      context: ./petplanet-api
#      dockerfile: Dockerfile
#    image: petplanet-api-image
#    container_name: petplanet-api-container
#    ports:
#      - "8885:8885"
