version: '3'
services:
  common:
    build:
      context: ./petplanet-common
      dockerfile: Dockerfile
    image: common-maven-image
  pet:
    build:
      context: ./petplanet-pet
      dockerfile: Dockerfile
    image: pet-image
    container_name: petplanet-pet
    ports:
      - "8881:8881"
    depends_on:
      - common
  post:
    build:
      context: ./petplanet-post
      dockerfile: Dockerfile
    image: post-image
    container_name: petplanet-post
    ports:
      - "8882:8882"
    depends_on:
      - common
  user:
    build:
      context: ./petplanet-user
      dockerfile: Dockerfile
    image: user-image
    container_name: petplanet-user
    ports:
      - "8883:8883"
    depends_on:
      - common
  api:
    build:
      context: ./petplanet-api
      dockerfile: Dockerfile
    image: api-image
    container_name: petplanet-api
    ports:
      - "8885:8885"
    depends_on:
      - common
