server:
  port: 7001
spring:
  datasource:
    url: jdbc:mysql://124.220.36.202:3306/petplanet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: petplanet
    password: petplanet

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:top/**/mapper/*.xml