spring:
  datasource:
    url: jdbc:mysql://124.220.36.202:3306/petplanet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: petplanet
    password: petplanet

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mq-transaction-test
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: top.zynorl.petplanet.user.deserializer.TransactionRecordDeserializer

  #redis
  redis:
    host: 124.220.36.202
    port: 6379
    password: 9Yi2L13Fd6z5p4lx8GwQEfuTKHjN
    database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
