spring:
  datasource:
    url: jdbc:mysql://124.220.36.202:3306/petplanet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: h5BZd1SUcrq348INbm7KHp6

  #redis
  redis:
    host: localhost
    port: 6379
    password: YOUR_REDIS_PASSWORD (如果需要)
    database: 0


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:top/**/mapper/*.xml
