spring:
  datasource:
    url: jdbc:mysql://124.220.36.202:3306/petplanet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: petplanet
    password: petplanet

  #redis
  redis:
    host: 124.220.36.202
    port: 6379
    password: 9Yi2L13Fd6z5p4lx8GwQEfuTKHjN
    database: 0


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:top/**/mapper/*.xml
