server:
  port: 8885
spring:
  application:
    name: commom-controller # ????
  cloud:
    nacos:
      discovery:
        server-addr: 124.220.36.202:8848 # nacos??
  # ????????
  datasource:
    # JDBC???
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.220.36.202:3306/petplanet
    username: root
    password: h5BZd1SUcrq348INbm7KHp6

    # ??????
    druid:
      initial-size: 2 # ????????????????0
      max-active: 10 # ??????????8
      min-idle: 1 # ???????
      max-wait: 2000 # ?????????????????
      pool-prepared-statements: false # ????preparedStatement????PSCache?PSCache???????????????????oracle??mysql??????
      max-pool-prepared-statement-per-connection-size: -1 # ???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
  servlet:
    multipart:
      #文件上传最大允许大小
      max-file-size: 100MB
      max-request-size: 100MB

#??mybatis???????
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #??????????????



minio:
  endpoint: http://124.220.36.202:9090
  accessKey: admin
  secretKey: admin1234
  bucketName: petplanet

#设置上传的最大信息